basePath: /api
definitions:
  entity.JoinMeetingRequest:
    properties:
      meeting_id:
        type: string
      user_name:
        type: string
    type: object
  entity.JoinMeetingResponse:
    properties:
      meeting_id:
        type: string
      user_id:
        type: string
      users_in_meeting:
        items:
          type: string
        type: array
    type: object
  entity.LeaveMeetingRequest:
    properties:
      meeting_id:
        type: string
      user_id:
        type: string
    type: object
  entity.Meeting:
    properties:
      created_at:
        type: string
      meeting_id:
        type: string
      meeting_name:
        type: string
      users:
        items:
          $ref: '#/definitions/entity.User'
        type: array
    type: object
  entity.User:
    properties:
      is_online:
        type: boolean
      user_id:
        type: string
      user_name:
        type: string
    type: object
  v1.response:
    properties:
      error:
        type: string
      message:
        type: string
    type: object
info:
  contact: {}
  description: zvonim backend
  title: Zvonim App
  version: "1.0"
paths:
  /healthz:
    get:
      operationId: healthz
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: Check server health
      tags:
      - common
  /meeting/{meeting_id}/info:
    get:
      description: Get meeting information and users list
      parameters:
      - description: Meeting ID
        in: path
        name: meeting_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Meeting'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Get meeting info
      tags:
      - meetings
  /meeting/{meeting_id}/ws:
    get:
      description: WebSocket endpoint для обмена WebRTC сигналами
      parameters:
      - description: Meeting ID
        in: path
        name: meeting_id
        required: true
        type: string
      - description: User ID
        in: query
        name: user_id
        required: true
        type: string
      responses: {}
      summary: WebSocket для сигналинга
      tags:
      - websocket
  /meeting/join:
    post:
      consumes:
      - application/json
      description: Create a new meeting or join existing one
      parameters:
      - description: Join meeting request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.JoinMeetingRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.JoinMeetingResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Join or create meeting
      tags:
      - meetings
  /meeting/leave:
    post:
      consumes:
      - application/json
      description: Leave the meeting
      parameters:
      - description: Leave meeting request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.LeaveMeetingRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Leave meeting
      tags:
      - meetings
schemes:
- https
- http
swagger: "2.0"
